# Site settings
name: 卷子的博客
email: 313052590@qq.com
author: kxZhou
url: https://kaixuanzhou.github.io/
resume_site: https://kaixuanzhou.github.io/
github: https://github.com/kaixuanzhou
baseurl: ""
description: 吾今虽欲自以为不足，而众已妄推之矣
meta_description: 卷子;个人博客;zkxuan;
motto: 博观而约取，厚积而薄发
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: kaixuanzhou
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: f0f7543f1763e147f327677dbc2978c2

FB:
  comments :
    provider : custom
    duoshuo:
        short_name : zkxuan
    disqus :
        short_name : zkxuan
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
